Date::DATE_FORMATS[:date]="%-m/%-d"
Date::DATE_FORMATS[:date2]="%m/%d"
Date::DATE_FORMATS[:hour_month]="%Y年%m月"
Date::DATE_FORMATS[:days]="%Y/%m/%d "
Time::DATE_FORMATS[:time]="%H:%M"
Time::DATE_FORMATS[:hour]="%H"
Time::DATE_FORMATS[:min]="%M"
